use crate::model::{SearchKind, Site, Step};

/// Shared fallback workflow for brokers without a custom checklist.
const GENERIC_STEPS: &[Step] = &[
    Step {
        title: "Search for a matching listing",
        body: "Use the generated search link and also search by phone, address, and name variants.",
    },
    Step {
        title: "Save evidence locally",
        body: "Paste profile URLs, matching details, and the date found into notes.",
    },
    Step {
        title: "Open the opt-out page",
        body: "Follow the broker's current removal form and complete any required verification.",
    },
    Step {
        title: "Confirm any email request",
        body: "Click confirmation links promptly and record the confirmation date.",
    },
    Step {
        title: "Recheck later",
        body: "Search again after the broker's stated processing window and mark the result.",
    },
];

/// Custom workflow for `FastBackgroundCheck`.
const FASTBACKGROUND_STEPS: &[Step] = &[
    Step {
        title: "Find your listing",
        body: "Search by name, phone, and address. Save every matching profile URL in notes.",
    },
    Step {
        title: "Open the opt-out form",
        body: "Enter your name and opt-out email, then complete the captcha.",
    },
    Step {
        title: "Confirm by email",
        body: "Click their email link within 24 hours.",
    },
    Step {
        title: "Submit matching details",
        body: "Use the same name, city, and address shown on the listing so they can identify the record.",
    },
    Step {
        title: "Verify removal",
        body: "Check the listing again after 3 days and record the date.",
    },
];

/// Custom workflow for Spokeo.
const SPOKEO_STEPS: &[Step] = &[
    Step {
        title: "Find the exact profile",
        body: "Search Spokeo and open the result that matches your phone number or address.",
    },
    Step {
        title: "Copy the profile URL",
        body: "Paste the profile URL into notes before you start the removal form.",
    },
    Step {
        title: "Open Spokeo opt-out",
        body: "Paste the profile URL and your email address, then complete the captcha.",
    },
    Step {
        title: "Confirm by email",
        body: "Click the confirmation link Spokeo sends.",
    },
    Step {
        title: "Check for no results",
        body: "Revisit the profile URL and search results after a few days.",
    },
];

/// Custom workflow for Whitepages.
const WHITEPAGES_STEPS: &[Step] = &[
    Step {
        title: "Search your listing",
        body: "Start from the suppression request page or search Whitepages by name and location.",
    },
    Step {
        title: "Select the matching record",
        body: "Use the listing that shows your current or old address, phone number, or relatives.",
    },
    Step {
        title: "Request removal",
        body: "Choose the removal or suppression option for that record.",
    },
    Step {
        title: "Complete verification",
        body: "Be ready for phone verification if their flow asks for it.",
    },
    Step {
        title: "Recheck free and premium results",
        body: "Search again after a few days and save what changed.",
    },
];

/// Broker catalog used by the workflow, discovery filters, and link helpers.
pub(crate) const SITES: &[Site] = &[
    Site {
        id: "fastbackgroundcheck",
        name: "FastBackgroundCheck",
        domain: "fastbackgroundcheck.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["captcha", "email confirmation"],
        summary: "Email-gated opt-out form. They send a link, then ask for matching record information.",
        caution: "Their own page says the email link expires after 24 hours and removal can take up to 3 days after submission.",
        opt_out_url: "https://www.fastbackgroundcheck.com/optout",
        search_kind: SearchKind::Direct("https://www.fastbackgroundcheck.com/name/"),
        steps: FASTBACKGROUND_STEPS,
    },
    Site {
        id: "spokeo",
        name: "Spokeo",
        domain: "spokeo.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["profile URL", "captcha", "email confirmation"],
        summary: "Requires a specific Spokeo profile URL, an email address, captcha, and email confirmation.",
        caution: "Spokeo listings may return when they refresh source data, so schedule a recurring check.",
        opt_out_url: "https://www.spokeo.com/optout",
        search_kind: SearchKind::GoogleSite,
        steps: SPOKEO_STEPS,
    },
    Site {
        id: "whitepages",
        name: "Whitepages",
        domain: "whitepages.com",
        category: "People search",
        difficulty: "Hard",
        signals: &["phone verification", "premium listings"],
        summary: "Suppression flow generally starts from their opt-out page and can require phone verification.",
        caution: "Whitepages and Whitepages Premium can behave like separate surfaces. Check both search results and premium-style listings.",
        opt_out_url: "https://www.whitepages.com/suppression-requests",
        search_kind: SearchKind::Direct("https://www.whitepages.com/name/"),
        steps: WHITEPAGES_STEPS,
    },
    Site {
        id: "beenverified",
        name: "BeenVerified",
        domain: "beenverified.com",
        category: "Background check",
        difficulty: "Medium",
        signals: &["email confirmation", "profile URL"],
        summary: "People-search and background-check site that commonly requires finding the exact listing first.",
        caution: "Check related brands and duplicate records after removal.",
        opt_out_url: "https://www.beenverified.com/app/optout/search",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "peoplefinders",
        name: "PeopleFinders",
        domain: "peoplefinders.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["profile URL", "email confirmation"],
        summary: "People-search site with name, phone, address, and relative matching.",
        caution: "Look for multiple records under old addresses or name variants.",
        opt_out_url: "https://www.peoplefinders.com/opt-out",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "truthfinder",
        name: "TruthFinder",
        domain: "truthfinder.com",
        category: "Background check",
        difficulty: "Medium",
        signals: &["suppression center", "email confirmation"],
        summary: "Background-check brand often connected to the same profile ecosystem as other search sites.",
        caution: "Search for old cities and aliases, not just current records.",
        opt_out_url: "https://www.truthfinder.com/opt-out/",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "intelius",
        name: "Intelius",
        domain: "intelius.com",
        category: "Background check",
        difficulty: "Medium",
        signals: &["suppression center", "email confirmation"],
        summary: "Background-check and people-search site with overlapping data sources.",
        caution: "If one profile is removed, search again for near-duplicate listings.",
        opt_out_url: "https://www.intelius.com/opt-out/",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "instantcheckmate",
        name: "Instant Checkmate",
        domain: "instantcheckmate.com",
        category: "Background check",
        difficulty: "Medium",
        signals: &["suppression center", "email confirmation"],
        summary: "Background-check site that can expose age, relatives, locations, and contact details.",
        caution: "Treat removal as recurring because background-check sites refresh data frequently.",
        opt_out_url: "https://www.instantcheckmate.com/opt-out/",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "ussearch",
        name: "US Search",
        domain: "ussearch.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["suppression center"],
        summary: "Older people-search brand that may share removal infrastructure with related companies.",
        caution: "Search for exact address snippets when name search is noisy.",
        opt_out_url: "https://www.ussearch.com/opt-out/",
        search_kind: SearchKind::GoogleNameAddress,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "radaris",
        name: "Radaris",
        domain: "radaris.com",
        category: "People search",
        difficulty: "Hard",
        signals: &["account or verification", "profile claiming"],
        summary: "People-search site with profile pages, relatives, addresses, and possible aliases.",
        caution: "Removal flows can be more involved than simple email-confirmed opt-outs.",
        opt_out_url: "https://radaris.com/page/how-to-remove",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "thatsthem",
        name: "ThatsThem",
        domain: "thatsthem.com",
        category: "Reverse lookup",
        difficulty: "Easy",
        signals: &["simple form"],
        summary: "Reverse phone, email, and address lookup site.",
        caution: "Phone and address searches may reveal different records.",
        opt_out_url: "https://thatsthem.com/optout",
        search_kind: SearchKind::PhonePath("https://thatsthem.com/phone/"),
        steps: GENERIC_STEPS,
    },
    Site {
        id: "cyberbackgroundchecks",
        name: "CyberBackgroundChecks",
        domain: "cyberbackgroundchecks.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["captcha", "email confirmation"],
        summary: "People-search site with detailed address and phone profiles.",
        caution: "Search exact phone and exact address because name results can be broad.",
        opt_out_url: "https://www.cyberbackgroundchecks.com/removal",
        search_kind: SearchKind::GooglePhoneOrName,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "searchpeoplefree",
        name: "SearchPeopleFree",
        domain: "searchpeoplefree.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["email confirmation"],
        summary: "People-search site that can show phone numbers, relatives, and addresses.",
        caution: "Search by phone after completing name-based removals.",
        opt_out_url: "https://www.searchpeoplefree.com/opt-out",
        search_kind: SearchKind::GooglePhoneOrName,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "truepeoplesearch",
        name: "TruePeopleSearch",
        domain: "truepeoplesearch.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["email confirmation", "record URL"],
        summary: "Free people-search site with phone, address, and relatives.",
        caution: "Record URLs can differ between name and phone searches.",
        opt_out_url: "https://www.truepeoplesearch.com/removal",
        search_kind: SearchKind::GooglePhoneOrName,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "fastpeoplesearch",
        name: "FastPeopleSearch",
        domain: "fastpeoplesearch.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["email confirmation", "record URL"],
        summary: "People-search site often indexed by phone and address.",
        caution: "Use exact phone searches to catch records missed by name.",
        opt_out_url: "https://www.fastpeoplesearch.com/removal",
        search_kind: SearchKind::GooglePhoneOrName,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "familytreenow",
        name: "FamilyTreeNow",
        domain: "familytreenow.com",
        category: "Genealogy",
        difficulty: "Easy",
        signals: &["simple form"],
        summary: "Genealogy-style people-search site that can expose relatives and historical addresses.",
        caution: "Historical addresses and family links may make records easy to identify.",
        opt_out_url: "https://www.familytreenow.com/optout",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "nuwber",
        name: "Nuwber",
        domain: "nuwber.com",
        category: "People search",
        difficulty: "Medium",
        signals: &["record URL", "email confirmation"],
        summary: "People-search site with profile URLs, contact details, and address history.",
        caution: "Check for duplicate records with middle initials or old locations.",
        opt_out_url: "https://nuwber.com/removal/link",
        search_kind: SearchKind::GoogleSite,
        steps: GENERIC_STEPS,
    },
    Site {
        id: "numlookup",
        name: "NumLookup",
        domain: "numlookup.com",
        category: "Reverse lookup",
        difficulty: "Easy",
        signals: &["phone lookup"],
        summary: "Reverse phone lookup site.",
        caution: "Phone-only sites may rehydrate from telecom or marketing data sources.",
        opt_out_url: "https://www.numlookup.com/optout",
        search_kind: SearchKind::PhonePath("https://www.numlookup.com/"),
        steps: GENERIC_STEPS,
    },
];
